version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/circleci-build
    executor: python/default
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m unittest tests/**/*.py
          name: Test
      - run:
          command: pipenv run coverage run --source=. -m unittest tests/**/*.py
          name: Coverage

workflows:
  main:
    jobs:
      - build-and-test
